### ISSUE TITLE
Add support for '3b8f8001804f0ca000000306030001000000006a' token

### ISSUE THREAD

**Issue by neopeeranat** [PeculiarVentures/fortify#253] opened 2019-11-06 04:08 UTC
Reader name: ACS ACR122 0
ATR: 3B8F8001804F0CA000000306030001000000006A

```js
{
   "cards": [{
   	"atr": "3B8F8001804F0CA000000306030001000000006A",
   	"name": "Token name",
   	"driver": "A6C219A0CD45422837FD69E22CF39F8E988A1359"
   }],
   "drivers": [{
   	"id": "A6C219A0CD45422837FD69E22CF39F8E988A1359",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B8F8001804F0CA000000306030001000000006A](https://smartcard-atr.appspot.com/parse?ATR=3B8F8001804F0CA000000306030001000000006A)

**Comment by rmhrisk** [comment] 2019-11-06 08:38
Can you tell us more about this token / card?

What PKCS11 library do you use with it?

What is it’s make and model?

**Comment by donskov** [comment] 2020-11-24 16:40
Closing as dupe of #125

**Closed by donskov** 2020-11-24 16:40 UTC
