### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by Chrischacon** [PeculiarVentures/fortify#191] opened 2019-07-01 22:08 UTC
Reader name: Athena ASEDrive IIIe USB 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "2CA594C6F696105357124C34926B82EBDDDD8F58"
   }],
   "drivers": [{
   	"id": "2CA594C6F696105357124C34926B82EBDDDD8F58",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-02 00:31
Closing as a dupe of: #173

If you can help with the additional details needed to add support it would be great.

**Closed by rmhrisk** 2019-07-02 00:31 UTC

**Comment by Chrischacon** [comment] 2019-07-02 21:48
Thanks

*Ing. Christian Stanley Chacón Barquero *
*(+506)88342020*
*(+506)22565674 *
*Email:  chrischacon@gmail.com <chrischacon@gmail.com>*
https://www.facebook.com/ChristianStanleyChaconBarquero






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rmhrisk** [comment] 2019-07-02 22:13
@Chrischacon can you help us with sharing the path to the PKCS#11 library you use with this card?

**Comment by Chrischacon** [comment] 2019-07-02 22:39
I have no idea what the question is.
I have very basic computer knowledge.

*Ing. Christian Stanley Chacón Barquero *
*(+506)88342020*
*(+506)22565674 *
*Email:  chrischacon@gmail.com <chrischacon@gmail.com>*
https://www.facebook.com/ChristianStanleyChaconBarquero






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rmhrisk** [comment] 2019-07-02 23:38
Where do you get the software for your national ID card? If you provide us a link we can probably figure it out.

**Comment by Chrischacon** [comment] 2019-07-03 00:14
I will try to explain, with my knowlegde.
I am a surveyor.
I am asociated to the NAtional Engeneer federation , which a mandatory
asociation to work,
This week they started the digital firm for the platform that requieres to
send and receive surveyor maps of lands.
That is why.

*Ing. Christian Stanley Chacón Barquero *
*(+506)88342020*
*(+506)22565674 *
*Email:  chrischacon@gmail.com <chrischacon@gmail.com>*
https://www.facebook.com/ChristianStanleyChaconBarquero






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rmhrisk** [comment] 2019-07-03 02:54
Thank you.

Do you have the URL to the firma solution you use?
