### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by Adolfo25071981** [PeculiarVentures/fortify#427] opened 2021-07-20 16:39 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "85F2C9663FC9B26307D1EF80CD21CEC33DCB511F"
   }],
   "drivers": [{
   	"id": "85F2C9663FC9B26307D1EF80CD21CEC33DCB511F",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2021-07-20 16:49
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by rmhrisk** 2021-07-20 16:49 UTC
