### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by dacuna0651** [PeculiarVentures/fortify#345] opened 2020-07-18 23:16 UTC
Reader name: Athena ASEDrive IIIe USB 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "10B34176626662973BAB1C763DC0EE3FCD0BE4F4"
   }],
   "drivers": [{
   	"id": "10B34176626662973BAB1C763DC0EE3FCD0BE4F4",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by dacuna0651** [comment] 2020-07-18 23:17
It works one day and the next not

**Comment by rmhrisk** [comment] 2020-07-18 23:21
@dacuna0651 can you provide us a log from fortify when it doesn't work and one more when it does.

You can enable logging in the fortify menu.

**Comment by donskov** [comment] 2020-11-24 16:54
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by donskov** 2020-11-24 16:54 UTC
