### ISSUE TITLE
Add `Don't ask again` checkbox

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify#122] opened 2018-10-10 04:40 UTC
![image](https://user-images.githubusercontent.com/7333669/46713489-9b0bc780-cc5f-11e8-9f06-45eb06ab700a.png)

**Comment by rmhrisk** [comment] 2018-10-10 06:32
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/121

**Closed** 2018-10-10 06:32 UTC
Labels: enhancement
