### ISSUE TITLE
Unable to open fortify tools in Chrome

### ISSUE THREAD

**Issue by Kharya1337** [PeculiarVentures/fortify#409] opened 2021-05-06 16:12 UTC
I'm trying to open Fortify tools in Chrome browser (Version 90.0.4430.93 (Official Build) (x86_64)), but it responds me with message `Server is offline. Wait until the connection is established`.
When I try to open fortify tools in another browser (e.g. Firefox v88.0.1 (64-bit)) it works fine and opens without any error.

**Comment by apilguk** [comment] 2021-07-08 14:39
I have the same issue
Chrome Version 91.0.4472.114 (Official Build) (arm64)
Fortify 1.8.2

**Comment by microshine** [comment] 2021-07-22 06:49
I installed Fortify v1.8.2 from fortifyapp.com. It works fine

![image](https://user-images.githubusercontent.com/7333669/126599556-403e1457-31de-4025-ae49-dcff46d6486d.png)
![image](https://user-images.githubusercontent.com/7333669/126599606-1e60900d-c91b-4320-b2b8-d5e224f1c462.png)

Maybe the problem is security permission and Chrome doesn't have access to local server

**Comment by donskov** [comment] 2021-09-09 09:57
The same situation for @Bonn2018.

**Comment by microshine** [comment] 2021-09-14 16:19
Please try:

### Reinstall SSL certificate
1. Open `~/.fortify` folder
2. Remove `cert.pem` and `cert.key` files
3. Restart Fortify application

### Add CA certificate to the Root CA store manually

CA certificate for the Fortify application is `~/.fortify/ca.pem`

- [Windows](https://docs.microsoft.com/en-us/skype-sdk/sdn/articles/installing-the-trusted-root-certificate#adding-certificate-snap-ins) (add certificate to the `Trusted Root Certification Authorities` store)
- [MacOS](https://www.eduhk.hk/ocio/content/faq-how-add-root-certificate-mac-os-x)
- [Mozilla Firefox](https://docs.vmware.com/en/VMware-Adapter-for-SAP-Landscape-Management/2.0.1/Installation-and-Administration-Guide-for-VLA-Administrators/GUID-0CED691F-79D3-43A4-B90D-CD97650C13A0.html)
- [NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/tools/NSS_Tools_certutil)
```
certutil -A -n "Fortify Local CA" -t "CT,c," -i <cert.pem> -d <certdir>
```

**Comment by donskov** [comment] 2022-06-20 16:15
Should be resolved in https://github.com/PeculiarVentures/fortify/releases/tag/1.8.4.

**Closed by donskov** 2022-06-20 16:15 UTC
