### ISSUE TITLE
Add support for '3b9f958131fe9f006646530532022571df000006000010' token

### ISSUE THREAD

**Issue by hirani7** [PeculiarVentures/fortify#303] opened 2020-03-17 13:57 UTC
Reader name: FT ePass2003Auto 0
ATR: 3B9F958131FE9F006646530532022571DF000006000010

```js
{
   "cards": [{
   	"atr": "3B9F958131FE9F006646530532022571DF000006000010",
   	"name": "Token name",
   	"driver": "85CD9E5ECFC7084F1F791A9960192B90133ED5EE"
   }],
   "drivers": [{
   	"id": "85CD9E5ECFC7084F1F791A9960192B90133ED5EE",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B9F958131FE9F006646530532022571DF000006000010](https://smartcard-atr.apdu.fr/parse?ATR=3B9F958131FE9F006646530532022571DF000006000010)

**Comment by donskov** [comment] 2020-11-24 16:42
Closing as dupe of #238

**Closed by donskov** 2020-11-24 16:42 UTC
