### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by jpmoraa** [PeculiarVentures/fortify#280] opened 2020-01-18 05:50 UTC
Reader name: Athena ASEDrive CCID 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "E003EDAF1A0E30E08DE3AD5EF39D3E0474B78FB4"
   }],
   "drivers": [{
   	"id": "E003EDAF1A0E30E08DE3AD5EF39D3E0474B78FB4",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.apdu.fr/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2020-01-18 07:21
Can you share some information about this device?

What make and model?

What is the fully qualified path and file name of the PKCS11 that you use with it?

**Comment by rmhrisk** [comment] 2020-01-18 07:23
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/173

**Closed by rmhrisk** 2020-01-18 07:23 UTC
