### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by pabloleon1930** [PeculiarVentures/fortify#508] opened 2022-06-24 17:52 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "121E9A893F0EA789777F5C31D82B766EF7853C4F"
   }],
   "drivers": [{
   	"id": "121E9A893F0EA789777F5C31D82B766EF7853C4F",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2022-06-24 17:58
Closing as a duplicate of https://github.com/PeculiarVentures/fortify/issues/372

We need a users assistance to add support for this token.

**Closed by rmhrisk** 2022-06-24 17:58 UTC
