### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by RonaldMesen** [PeculiarVentures/fortify#296] opened 2020-03-04 01:27 UTC
Reader name: OMNIKEY AG 3121 USB
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "FD663C6E6BFDE763010A6A5E9830A70057E748B3"
   }],
   "drivers": [{
   	"id": "FD663C6E6BFDE763010A6A5E9830A70057E748B3",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-03-04 04:01
Can you share more information with us about this token?

Which smartcard is this?
Which PKCS11 library do you use with it?
What is the fully qualified path for the PkCS11 library?

**Comment by donskov** [comment] 2020-11-24 16:54
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by donskov** 2020-11-24 16:54 UTC
