### ISSUE TITLE
Add support for '3b9f958131fe9f006646530501001171df000000000013' token

### ISSUE THREAD

**Issue by andreibratuleanu21** [PeculiarVentures/fortify#265] opened 2019-12-15 13:34 UTC
Reader name: FT ePass2003Auto
ATR: 3B9F958131FE9F006646530501001171DF000000000013

```js
{
   "cards": [{
   	"atr": "3B9F958131FE9F006646530501001171DF000000000013",
   	"name": "Token name",
   	"driver": "6ABDEF58F95839BD1754AD1FCCF2756B6798193A"
   }],
   "drivers": [{
   	"id": "6ABDEF58F95839BD1754AD1FCCF2756B6798193A",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B9F958131FE9F006646530501001171DF000000000013](https://smartcard-atr.appspot.com/parse?ATR=3B9F958131FE9F006646530501001171DF000000000013)

**Comment by donskov** [comment] 2020-11-24 16:47
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/238

**Closed by donskov** 2020-11-24 16:47 UTC
