### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by Melvin06** [PeculiarVentures/fortify#181] opened 2019-07-01 17:06 UTC
Reader name: Athena ASEDrive V3CR 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "04AD55047E7D1099F5A86E6AE86DFB757DD40D38"
   }],
   "drivers": [{
   	"id": "04AD55047E7D1099F5A86E6AE86DFB757DD40D38",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-01 17:12
@Melvin06 We need the path to the PKCS#11 library to add support for this card. Please provide it.

In the meantime, I am closing this as a dupe of https://github.com/PeculiarVentures/fortify/issues/173

**Closed** 2019-07-01 17:14 UTC
