### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by dacuna0651** [PeculiarVentures/fortify#373] opened 2020-10-22 17:03 UTC
Reader name: Athena ASEDrive IIIe USB 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "3ECCF3E4DF5B002FF2BABE5A27738CFB324C07BD"
   }],
   "drivers": [{
   	"id": "3ECCF3E4DF5B002FF2BABE5A27738CFB324C07BD",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-10-23 00:35
Thanks for the issue dacuna.

Can you give us a bit more information about this device?

Who makes it?
What model is it?
What PKCS#11 library does it use?

**Comment by rmhrisk** [comment] 2020-10-23 00:36
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/343

**Closed by rmhrisk** 2020-10-23 00:36 UTC

**Comment by dacuna0651** [comment] 2020-10-23 00:42
Thank you Mr Ryan, I re-install the program, and it is working well.

Daniel Acuña Ortega
IT 5061
8565 4414


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
