### ISSUE TITLE
Add support for '3b9f958131fe9f006646530501001171df000006000015' token

### ISSUE THREAD

**Issue by hirani7** [PeculiarVentures/fortify#304] opened 2020-03-19 11:46 UTC
Reader name: FT ePass2003Auto 0
ATR: 3B9F958131FE9F006646530501001171DF000006000015

```js
{
   "cards": [{
   	"atr": "3B9F958131FE9F006646530501001171DF000006000015",
   	"name": "Token name",
   	"driver": "683317A58D844DE52A5312BFA3D69CC5D82340A6"
   }],
   "drivers": [{
   	"id": "683317A58D844DE52A5312BFA3D69CC5D82340A6",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B9F958131FE9F006646530501001171DF000006000015](https://smartcard-atr.apdu.fr/parse?ATR=3B9F958131FE9F006646530501001171DF000006000015)

**Comment by rmhrisk** [comment] 2020-03-19 16:51
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/146

**Closed by rmhrisk** 2020-03-19 16:51 UTC
