### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by jpmoraa** [PeculiarVentures/fortify#279] opened 2020-01-18 04:22 UTC
Reader name: Athena ASEDrive CCID 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "562B521AB1823FB5F23CE194E8CB4887CFB8DD98"
   }],
   "drivers": [{
   	"id": "562B521AB1823FB5F23CE194E8CB4887CFB8DD98",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.apdu.fr/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2020-01-18 05:32
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/278

**Comment by rmhrisk** [comment] 2020-01-18 05:34
Can you tell me more about the device? It’s make, model and the fully qualified path to the PKCS11 you use with this.

**Closed** 2020-01-18 05:34 UTC
