### ISSUE TITLE
Add support for '3b8f8001804f0ca000000306030001000000006a' token

### ISSUE THREAD

**Issue by vbhatkotti** [PeculiarVentures/fortify#271] opened 2020-01-13 19:13 UTC
Reader name: MANTRA MANTRA CCID-CL 0
ATR: 3B8F8001804F0CA000000306030001000000006A

```js
{
   "cards": [{
   	"atr": "3B8F8001804F0CA000000306030001000000006A",
   	"name": "Token name",
   	"driver": "766DCFB318F9F143CD40A7E1E9A60646C7FD92BA"
   }],
   "drivers": [{
   	"id": "766DCFB318F9F143CD40A7E1E9A60646C7FD92BA",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B8F8001804F0CA000000306030001000000006A](https://smartcard-atr.apdu.fr/parse?ATR=3B8F8001804F0CA000000306030001000000006A)

**Comment by rmhrisk** [comment] 2020-01-13 19:19
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/125

**Closed by rmhrisk** 2020-01-13 19:19 UTC
