### ISSUE TITLE
Add support for '3bff1300008131fe450031b9640444ecc17394018082900012' token

### ISSUE THREAD

**Issue by StipT** [PeculiarVentures/fortify#309] opened 2020-04-13 11:46 UTC
Croatian eID
Reader name: Generic Smart Card Reader Interface 0
ATR: 3BFF1300008131FE450031B9640444ECC17394018082900012
lib path(windows): C:\Program Files\AKD\eID Middleware\pkcs11\AkdEidPkcs11_64.dll

```js
{
   "cards": [{
   	"atr": "3BFF1300008131FE450031B9640444ECC17394018082900012",
   	"name": "Token name",
   	"driver": "45CC02170E455F906980A13181B255E9D6F74FD3"
   }],
   "drivers": [{
   	"id": "45CC02170E455F906980A13181B255E9D6F74FD3",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFF1300008131FE450031B9640444ECC17394018082900012](https://smartcard-atr.apdu.fr/parse?ATR=3BFF1300008131FE450031B9640444ECC17394018082900012)

**Comment by rmhrisk** [comment] 2020-04-21 05:17
Sorry for not responding yet, been busy. Why close this

**Comment by donskov** [comment] 2020-11-24 16:48
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/292

**Closed by donskov** 2020-11-24 16:48 UTC
