### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by NAVIGLEZ** [PeculiarVentures/fortify#349] opened 2020-07-31 01:13 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "FE72534DDA8A98C1CB71BE1CF772DCEE44BA576B"
   }],
   "drivers": [{
   	"id": "FE72534DDA8A98C1CB71BE1CF772DCEE44BA576B",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-07-31 06:48
Can you tell us more about this smart card?

What is it’s make and model?

What PKCS11 library do you use with it?

**Comment by donskov** [comment] 2020-11-24 16:55
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by donskov** 2020-11-24 16:55 UTC
