### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by pabloleon1930** [PeculiarVentures/fortify#507] opened 2022-06-24 12:11 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "421275A0A5CB73BAD327352C49A3FE0CE4614D42"
   }],
   "drivers": [{
   	"id": "421275A0A5CB73BAD327352C49A3FE0CE4614D42",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by microshine** [comment] 2022-06-24 12:16
Dupe of https://github.com/PeculiarVentures/fortify/issues/372

@pabloleon1930 Could you update your `~/.fortify/card.json` like described in https://github.com/PeculiarVentures/fortify/issues/372#issuecomment-1163597069 ?

**Closed** 2022-07-05 20:01 UTC
