### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by EduardoMoralesValle** [PeculiarVentures/fortify#201] opened 2019-07-02 16:04 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "3AA4C5AF329E82BED3C12FD5B96525C3DFB1EE6E"
   }],
   "drivers": [{
   	"id": "3AA4C5AF329E82BED3C12FD5B96525C3DFB1EE6E",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-02 16:53
Closing as a duplicate of https://github.com/PeculiarVentures/fortify/issues/173

Please provide us details on the PKCS#11 library used with this token so we can add support for it.

**Closed** 2019-07-02 16:53 UTC
