### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by dacuna0651** [PeculiarVentures/fortify#342] opened 2020-07-03 02:03 UTC
Reader name: Athena ASEDrive IIIe USB 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "566506009DA5E0A79D9EE2972CBA741D543589E4"
   }],
   "drivers": [{
   	"id": "566506009DA5E0A79D9EE2972CBA741D543589E4",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-07-03 04:45
Can you tell us more about this card?

Does it contain certificates?

What PKCS11 library do you use with it?

What is the make/model name?

**Comment by donskov** [comment] 2020-11-24 16:54
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by donskov** 2020-11-24 16:54 UTC
