### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by Breiner1128** [PeculiarVentures/fortify#316] opened 2020-04-28 22:43 UTC
Reader name: Bit4id IDone 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "00C52D05F1E3FF4EB01B47896FB4B55A4ECD499D"
   }],
   "drivers": [{
   	"id": "00C52D05F1E3FF4EB01B47896FB4B55A4ECD499D",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-04-28 23:10
This appears to be the “ebee card“ is that right?

**Comment by microshine** [comment] 2020-04-30 10:42
Closing as dupe of #296

**Closed by microshine** 2020-04-30 10:42 UTC
