### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by Topojef** [PeculiarVentures/fortify#180] opened 2019-07-01 16:12 UTC
Reader name: Athena ASEDrive V3CR 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "802528F452D39DE63DBFF8C183CA134DA6B2E3C9"
   }],
   "drivers": [{
   	"id": "802528F452D39DE63DBFF8C183CA134DA6B2E3C9",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-01 16:23
@Topojef this appears to be "Digital Signature Costa Rica (eID)"

What is the path to the PKCS#11 you use with this card?

**Comment by rmhrisk** [comment] 2019-07-01 16:28
We still need this information to add support but closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/173

**Closed by rmhrisk** 2019-07-01 16:28 UTC
