### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by pabloleon1930** [PeculiarVentures/fortify#509] opened 2022-07-04 14:07 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "FAD958819332E10AA39864232260DAA87AF1F470"
   }],
   "drivers": [{
   	"id": "FAD958819332E10AA39864232260DAA87AF1F470",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by microshine** [comment] 2022-07-04 14:10
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/372

Do you use `/usr/local/lib/libASEP11.dylib` for your token?

**Closed by microshine** 2022-07-04 14:10 UTC
