### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by Hector-Chaves-Alfaro** [PeculiarVentures/fortify#468] opened 2022-02-10 19:26 UTC
Reader name: Athena ASEDrive V3CR 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "D0B052A2F9A290E75B7CC79EA1E8E7FA2F9FAA2F"
   }],
   "drivers": [{
   	"id": "D0B052A2F9A290E75B7CC79EA1E8E7FA2F9FAA2F",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by microshine** [comment] 2022-02-10 21:39
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by microshine** 2022-02-10 21:39 UTC
