### ISSUE TITLE
Add support for '3b8f800100664653051000ff71df000000000039' token

### ISSUE THREAD

**Issue by richardabbott52** [PeculiarVentures/fortify#189] opened 2019-07-01 20:35 UTC
Reader name: Feitian R502 Contactless Reader 0
ATR: 3B8F800100664653051000FF71DF000000000039

```js
{
   "cards": [{
   	"atr": "3B8F800100664653051000FF71DF000000000039",
   	"name": "Token name",
   	"driver": "2B8CBEFBD15ED46E61967E29E2D8F7DB938BF91C"
   }],
   "drivers": [{
   	"id": "2B8CBEFBD15ED46E61967E29E2D8F7DB938BF91C",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B8F800100664653051000FF71DF000000000039](https://smartcard-atr.appspot.com/parse?ATR=3B8F800100664653051000FF71DF000000000039)

**Comment by rmhrisk** [comment] 2019-07-02 00:33
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/190

**Closed** 2019-07-02 05:06 UTC
