### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by Adolfo25071981** [PeculiarVentures/fortify#368] opened 2020-10-13 21:58 UTC
Reader name: Athena ASEDrive CCID 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "FD262B4B050421E781C34E5DEC80F2F1CA16C345"
   }],
   "drivers": [{
   	"id": "FD262B4B050421E781C34E5DEC80F2F1CA16C345",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-10-13 22:04
Can you give us more information about this card?

What is its make and model?

What PKCS#11 library do you use with it?

**Comment by donskov** [comment] 2020-11-24 16:55
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by donskov** 2020-11-24 16:55 UTC
