### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by arojas99** [PeculiarVentures/fortify#237] opened 2019-07-31 20:17 UTC
Reader name: miniLector Pocket V2 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "FB01EA29B42E2B5DBB14F472F2678E54511FE233"
   }],
   "drivers": [{
   	"id": "FB01EA29B42E2B5DBB14F472F2678E54511FE233",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-08-01 01:42
This appears to be a “Digital Signature Costa Rica (eID)”

**Comment by rmhrisk** [comment] 2020-01-17 23:52
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/173

**Closed by rmhrisk** 2020-01-17 23:52 UTC
