### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by RonaldMesen** [PeculiarVentures/fortify#298] opened 2020-03-04 02:04 UTC
Reader name: OMNIKEY AG 3121 USB
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "1D02BD2ADB704CF29D97413B0FE5CBA262D8A445"
   }],
   "drivers": [{
   	"id": "1D02BD2ADB704CF29D97413B0FE5CBA262D8A445",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-03-04 04:02
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/296

**Closed by rmhrisk** 2020-03-04 04:02 UTC
