### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by Hector-Chaves-Alfaro** [PeculiarVentures/fortify#463] opened 2022-01-07 20:40 UTC
Reader name: Athena ASEDrive V3CR 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "1BB11C60EE266DD4F639C56BD9DEFC19BB6987D0"
   }],
   "drivers": [{
   	"id": "1BB11C60EE266DD4F639C56BD9DEFC19BB6987D0",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2022-01-13 22:03
Closing as a dupe of : https://github.com/PeculiarVentures/fortify/issues/372

Please provide more info there.

**Closed** 2022-01-25 13:58 UTC
