### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by Breiner1128** [PeculiarVentures/fortify#313] opened 2020-04-23 16:55 UTC
Reader name: Bit4id IDone 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "A01E042EEB1FFEC9A3470249697660E708516F09"
   }],
   "drivers": [{
   	"id": "A01E042EEB1FFEC9A3470249697660E708516F09",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by rmhrisk** [comment] 2020-04-23 21:36
Can you tell us a bit about this device? [This](https://www.ebeeoffice.ca/ebee-home/public) claims it is an "ebe card" but the website for that seems to have gone away.

Do you know if the associated program still exists?

Do you know what PKCS#11 library to use is?

Is there anything else you can tell us?

**Comment by rmhrisk** [comment] 2020-04-23 21:38
Found this also: https://www.journaldemontreal.com/2014/11/29/rip-le-coffre-fort-virtuel-1

**Comment by microshine** [comment] 2020-04-30 10:41
Closing as dupe of #296

**Closed by microshine** 2020-04-30 10:41 UTC
