### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by dacuna0651** [PeculiarVentures/fortify#343] opened 2020-07-11 21:49 UTC
Reader name: Athena ASEDrive IIIe USB 0
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "095DD5EC8E003674442A7A47845A81E8A5FE16CF"
   }],
   "drivers": [{
   	"id": "095DD5EC8E003674442A7A47845A81E8A5FE16CF",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.appspot.com/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by dacuna0651** [comment] 2020-07-11 21:49
Token not supported

**Comment by rmhrisk** [comment] 2020-07-12 03:19
@dacuna0651 can you tell us more about this token?

Who makes it?
What is the model?
Do you use this for signing, encrypting or logging into a service?
Do you know if it has a certificate on it?
Do you know if it has a PKCS#11 library and if so what is the file name for it?

**Comment by dacuna0651** [comment] 2020-07-12 18:02
I have a token athena Model: ASEDrive V3
S/N R10901-041411129

It does not work



Daniel Acuña Ortega
IT 5061
8565 4414

**Comment by rmhrisk** [comment] 2020-07-12 22:35
Thank you very much for your quick response.

What I need is information about the card you place in the reader (ASEDrive V3).

**Comment by dacuna0651** [comment] 2020-07-13 00:08
The card is from digital firm of National Bank of Costa Rica



Daniel Acuña Ortega
IT 5061
8565 4414

**Comment by dacuna0651** [comment] 2020-07-13 00:09
https://soportefirmadigital.com/web/es/

Daniel Acuña Ortega
IT 5061
8565 4414

**Comment by rmhrisk** [comment] 2020-07-13 01:24
Thank you. With this link we may be able to get it to work. We will try this week.

**Comment by dacuna0651** [comment] 2020-07-13 01:31
Thank you

Daniel Acuña Ortega
IT 5061
8565 4414

**Comment by rmhrisk** [comment] 2020-07-13 07:34
It seems that to get the software we need a “card ID”.

From the documentation we found nd for the software it seems that this software may only have windows middleware.


Would it be possible for you to share your fortify log with us?

**Comment by rmhrisk** [comment] 2020-10-23 00:37
Still need a log to debug this.

**Comment by donskov** [comment] 2020-11-24 16:54
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372

**Closed by donskov** 2020-11-24 16:54 UTC
