### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by JdCW-0576** [PeculiarVentures/fortify#193] opened 2019-07-02 02:10 UTC
Reader name: Athena ASEDrive V3CR 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "64DF3C0C06F0258991F031ED1328A67E9AACFC32"
   }],
   "drivers": [{
   	"id": "64DF3C0C06F0258991F031ED1328A67E9AACFC32",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-02 04:26
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/173

If you have the path to this PKCS#11 library we would appreciate it.

**Closed** 2019-07-02 04:26 UTC
