### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by mariocordero19** [PeculiarVentures/fortify#277] opened 2020-01-17 23:39 UTC
Reader name: Athena ASEDrive CCID 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "003AA727FB13CEA2DA73F5532AE7B882BE5B6D59"
   }],
   "drivers": [{
   	"id": "003AA727FB13CEA2DA73F5532AE7B882BE5B6D59",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2020-01-17 23:49
@mariocordero19 can you look at https://github.com/PeculiarVentures/fortify/issues/248 and see if those changes work for you? 

Closing this as dupe of that issue

**Comment by rmhrisk** [comment] 2020-01-17 23:51
Sorry, @mariocordero19 can you tell us more about this device? this issue appears to be dupe of https://github.com/PeculiarVentures/fortify/issues/237 so I am closing this bug; please comment in there.

**Closed by rmhrisk** 2020-01-17 23:51 UTC
