### ISSUE TITLE
Add support for '3b7f96000080318065b0850300ef120ffe829000' token

### ISSUE THREAD

**Issue by sl45sms** [PeculiarVentures/fortify#154] opened 2019-04-10 06:34 UTC
Reader name: Gemalto PC Twin Reader (72B7CFD3) 00 00
ATR: 3B7F96000080318065B0850300EF120FFE829000

```js
{
   "cards": [{
   	"atr": "3B7F96000080318065B0850300EF120FFE829000",
   	"name": "Token name",
   	"driver": "AFAF9FC96E85627C1F912DD476CF4A21570C0BC2"
   }],
   "drivers": [{
   	"id": "AFAF9FC96E85627C1F912DD476CF4A21570C0BC2",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7F96000080318065B0850300EF120FFE829000](https://smartcard-atr.appspot.com/parse?ATR=3B7F96000080318065B0850300EF120FFE829000)

**Comment by rmhrisk** [comment] 2019-04-10 14:39
@Panagiotis can you share some details about this card?

- what PKCS 11 library do you use with it and what is the path?
- what is the make and model of the device?

**Comment by rmhrisk** [comment] 2019-04-10 14:40
It looks like it might be “Gemalto IDPrime MD 840” is that right? Do you use the SAC client with it?

**Comment by rmhrisk** [comment] 2019-04-10 16:22
Closing as dupe of https://github.com/PeculiarVentures/fortify/issues/133

**Closed by rmhrisk** 2019-04-10 16:23 UTC
