### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by Carlosgv1977** [PeculiarVentures/fortify#198] opened 2019-07-02 15:34 UTC
Reader name: Athena ASEDrive CCID 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "9BCF39F556D03F55B1231009F639E62D03B20EF1"
   }],
   "drivers": [{
   	"id": "9BCF39F556D03F55B1231009F639E62D03B20EF1",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-02 16:54
Closing as a duplicate of https://github.com/PeculiarVentures/fortify/issues/173

Please provide us details on the PKCS#11 library used with this token so we can add support for it.

**Closed by rmhrisk** 2019-07-02 16:54 UTC
