### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by fgpadilla** [PeculiarVentures/fortify#192] opened 2019-07-01 23:16 UTC
Reader name: Athena ASEDrive V3CR 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "13EAD28024EA9E233C246507448FBB4699B0D98F"
   }],
   "drivers": [{
   	"id": "13EAD28024EA9E233C246507448FBB4699B0D98F",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment] 2019-07-02 00:30
Closing as a dupe of: #173

If you can help with the additional details needed to add support it would be great.

**Closed by rmhrisk** 2019-07-02 00:30 UTC
